name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build APK with Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/hostcwd \
            kivy/buildozer \
            buildozer android debug --allow-root
