name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build APK with Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/hostcwd \
            -e ANDROID_SDK_ROOT=/home/user/.buildozer/android/platform/android-sdk \
            kivy/buildozer \
            bash -c "yes | sdkmanager --licenses && buildozer android debug --allow-root"
